name: Build Gradle Project

on:
  push:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  say-hello:
    name: Say Hello
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project source
        uses: actions/checkout@v4

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Generate Java Code
        run: |
          ./gradlew :generateHelloWorld:generateJava --scan

      - name: Build Greetings
        run: |
          ./gradlew :Greetings:build --scan

      - name: Build HelloWorld
        run: |
          ./gradlew :HelloWorld:build --scan

      - name: Run Applications
        run: |
          ./gradlew :Greetings:run
          ./gradlew :HelloWorld:run